<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vocabulary Export</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 40px;
            color: #000;
        }

        header {
            font-size: 10px;
            margin-bottom: 20px;
            text-align: left;
        }

        footer {
            font-size: 10px;
            position: fixed;
            bottom: 20px;
            left: 40px;
            right: 40px;
            text-align: center;
            color: #777;
        }

        main {
            text-align: left;
        }

        h2 {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        h3 {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        p {
            font-size: 12px;
            margin-bottom: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
        }

        th {
            background-color: #f0f0f0;
        }

        .type {
            color: green;
            font-weight: bold;
        }

        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 6px;
            color: white;
            font-size: 10px;
            font-weight: bold;
        }

        .badge-advanced {
            background-color: #dc3545;
        }

        .badge-intermediate {
            background-color: #ffc107;
            color: #000;
        }

        .badge-beginner {
            background-color: #28a745;
        }

        .page {
            font-weight: bold;
        }
    </style>
</head>
<body>

<header>
    ardianjafar46@gmail.com |
    <a href="https://linkedin.com/in/ardianjafar" target="_blank">linkedin.com/in/ardianjafar</a> |
    <a href="https://manyan.site" target="_blank">manyan.site</a> |
    WhatsApp: +62 822-4595-9024
</header>

<main>
    <h2>Vocabulary List</h2>
    <h3>Let’s study hard, build our future for a better life</h3>
    <p>Below is the most frequently used vocabulary list. We hope you enjoy studying and learning new words!</p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Word En</th>
                <th>Word Id</th>
                <th>Type</th>
                <th>Example En</th>
                <th>Example Id</th>
                <th>Level</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($words as $index => $word)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $word->word_en }}</td>
                    <td>{{ $word->word_id }}</td>
                    <td class="type">{{ $word->type }}</td>
                    <td>{{ $word->example_en }}</td>
                    <td>{{ $word->example_id }}</td>
                    <td>
                        <span class="badge badge-{{ strtolower($word->level) }}">
                            {{ $word->level }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</main>

<footer>
    Thanks for visiting our page – Generated by manyan.site | Page <span class="page"></span>
</footer>

</body>
</html>
